version: "3.7"

services:
  elasticsearch:
    image: elasticsearch:7.17.18
    container_name: elasticsearch-morfeo
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - 9200:9200
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    container_name: redis-morfeo

  mysql:
    image: mysql:8.0
    container_name: mysql-morfeo
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: morfeo_development
      MYSQL_USER: morfeo
      MYSQL_PASSWORD: morfeo_pass
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
